public-site/docs/src/other/release/index.md
Added Sondre to the team section
=> Update release info

public-site/docs/src/docs/topic-runtime-env/index.md, public-site/docs/src/guides/deploy-only/index.md, public-site/docs/src/guides/index.md, public-site/docs/src/index.md, public-site/docs/src/start/config-your-app/index.md, public-site/docs/src/start/getting-access/index.md, public-site/docs/src/start/index.md, public-site/docs/src/start/radix-clusters/index.md, public-site/docs/src/start/radix-concepts/index.md, public-site/docs/src/start/registering-app/index.md, public-site/docs/src/start/requirements/index.md, public-site/docs/src/start/what-is-radix/index.md, public-site/docs/src/start/workflows/index.md
=> chng radixconfig.yaml ref

public-site/docs/src/docs/topic-uptime/index.md, public-site/docs/src/other/community/index.md, public-site/docs/src/start/index.md, public-site/docs/src/start/what-is-radix/index.md
Updated links to the new issues repo
=> radix-platform/issues to radix/issues

public-site/docs/src/other/release/index.md
Missing information in the Whats new page
=> 2023 info added

public-site/docs/src/docs/topic-dynatrace-int/index.md
=> add warning about Dynatrace support on radix

public-site/docs/docs/topic-docker/index.md, public-site/docs/docs/topic-releases/index.md, public-site/docs/guides/alerting/index.md, public-site/docs/guides/authentication/index.md, public-site/docs/guides/deploy-only/example-github-action-building-and-deploying-application.md, public-site/docs/guides/deploy-only/example-github-action-to-create-radix-deploy-pipeline-job.md, public-site/docs/guides/deploy-only/example-github-action-using-ad-service-principal-access-token.md, public-site/docs/guides/deploy-only/index.md, public-site/docs/guides/docker-useradd/index.md, public-site/docs/guides/enable-and-disable-components/index.md, public-site/docs/guides/monitoring/index.md, public-site/docs/guides/workload-identity/index.md, public-site/docs/radix-config/index.md
- Add info about `emptyDir` and `readOnlyFileSystem` in `Radix Config`
- Removed leftover property `sidebarDepth` from vuepress
=> First iteration immutable filesystem info

public-site/docs/docs/topic-runtime-env/index.md, public-site/docs/start/index.md
=> Small updates

radixconfig.yaml
Run with readonly root filesystem
=> added readonly root filesystem

public-site/package-lock.json, public-site/package.json
Update to latest version of docusaurus to resolve reported vulnerabilities
=> update package versions

.github/pull_request_template.md
=> add security option to PR template

radixconfig.yaml
nginx requires tmp directory to be writable
=> configure tmp volume for nginx

public-site/docs/guides/jobs/job-manager-and-job-api.md, public-site/docs/guides/jobs/notifications.md
=> extend-job-api-model-status

public-site/docs/guides/jobs/job-manager-and-job-api.md
=> add-status

public-site/docs/guides/apply-config/index.md, public-site/sidebars.ts
=> apply-config-pipeline-job

public-site/docs/guides/jobs/job-manager-and-job-api.md
=> Fixed pod and job statuses

public-site/docusaurus.config.ts, public-site/package-lock.json, public-site/package.json
=> fix-search

public-site/Dockerfile, public-site/Makefile, radixconfig.yaml
=> fix-search2

public-site/docs/guides/sub-pipeline/example-pipeline-with-azure-workload-identity.md, public-site/docs/guides/sub-pipeline/example-pipeline-with-env-vars-for-envs.md, public-site/docs/guides/sub-pipeline/example-pipeline-with-env-vars.md, public-site/docs/radix-config/index.md
=> docs-about-sub-pipeline-vars-and-identity

public-site/docs/docs/topic-docker/index.md
=> add-readonly-fs-info-for-builds

public-site/Dockerfile, public-site/dev.Dockerfile
Update to node20.14.0-alpine3.20
=> security - update to node 20.14.0

public-site/docs/docs/topic-releases/index.md, public-site/docs/radix-config/index.md
=> Fix Keda Cron example

radixconfig.yaml
=> use arm64 in all environments

public-site/docs/radix-config/index.md, public-site/docusaurus.config.ts
- Add documentaion about ingress allow list
- Add security related meta tags
=> Documentation for ingress allow list

public-site/docusaurus.config.ts
=> fix security settings in meta tags

public-site/docusaurus.config.ts
add unsafe-inline to CSP script-src
=> allow unsafe-inline in CSP

radixconfig.yaml
=> Update radixconfig.yaml - change req Memory and CPU

public-site/docs/radix-config/index.md
=> fix spelling

public-site/docs/docs/topic-private-link/index.md, public-site/docs/guides/private-link/index.md, public-site/sidebars.ts
=> Update private link documentation

public-site/docs/community/index.md, public-site/docs/docs/topic-releases/index.md
=> Updated email and release register

public-site/docs/guides/external-alias/index.md
Added info about CAA record verificate for external DNS certificate automation
=> add info about CAA record in certificate automation

radixconfig.yaml
[#1315
](https://github.com/equinor/radix-platform/issues/1315)
=> Set CPU limit

public-site/docs/docs/topic-radix-cli/index.md, public-site/docs/docs/topic-releases/index.md
=> Corrected commands, added get jobs commands info

public-site/docs/docs/topic-releases/index.md, public-site/docs/radix-config/index.md
=> Replicas on component level

public-site/docs/radix-config/index.md
Fix incorrect placement of properties in the ingress config example
=> fix incorrect placement of ingress properties

public-site/docs/docs/topic-logs/index.md
=> What is logged

public-site/docs/docs/topic-releases/index.md, public-site/docs/guides/build-secrets/index.md, public-site/docs/radix-config/index.md
=> feat: Update documentation for BuildKit usage

public-site/docs/docs/topic-releases/index.md, public-site/docs/radix-config/index.md
Added docs about proxyBufferSize in network.ingress.public
=> Add docs for proxyBufferSize

public-site/docs/docs/topic-releases/index.md, public-site/docs/guides/jobs/configure-jobs.md, public-site/docs/guides/jobs/job-manager-and-job-api.md, public-site/docs/radix-config/index.md
=> Info about runtime node types

public-site/docs/docs/topic-radix-cli/index.md, public-site/docs/docs/topic-releases/index.md, public-site/docs/docs/topic-runtime-env/index.md, public-site/docs/guides/environment-variables/index.md, public-site/docs/guides/jobs/environment-variables.md, public-site/docs/radix-config/index.md, public-site/docs/start/radix-concepts/index.md
=> 1205 refresh build kit cache

public-site/docs/docs/topic-radix-cli/index.md, public-site/docs/docs/topic-releases/index.md, public-site/docs/radix-config/index.md
=> Info about radixconfig environment.build.fromType

public-site/docs/docs/topic-releases/index.md, public-site/docs/radix-config/index.md
=> Info about command and args

public-site/docs/docs/topic-radix-cli/index.md, public-site/docs/guides/build-and-deploy/index.md, public-site/docs/radix-config/index.md
update Radix CLI docs
update src and dockerfileName in radixconfig
Update build-deploy guide
Update Radix CLI documentation for build-deploy pipeline
Update `src` and `dockerfileName` info in radixconfig
=> docs: update documentation about build-deploy pipeline

public-site/docs/docs/topic-radix-cli/index.md, public-site/docs/guides/deploy-only/example-github-action-to-create-radix-deploy-pipeline-job.md
=> Info about github.sha

public-site/docs/docs/topic-releases/index.md, public-site/docs/radix-config/index.md
=> Info about systemManaged redis

catalog-info.yaml
This PR fixes the indenting error in the catalog-info.yaml file and makes it valid yaml
=> Fix indenting in catalog-info.yaml to make it valid

catalog-info.yaml
This PR fixes the 'tags' issue in the catalog-info file.
=> Fix error on the tags element by removing it for now

public-site/docs/radix-config/index.md
=> Update gpu nvidia 1 v1 node

examples/radix-example-oauth-proxy/api/Dockerfile, examples/radix-example-oauth-proxy/api/package-lock.json, examples/radix-example-oauth-proxy/api/package.json, examples/radix-example-vite-spa-env-variables/Dockerfile, examples/radix-example-vite-spa-env-variables/package-lock.json, examples/radix-example-vite-spa-env-variables/package.json, public-site/package-lock.json, public-site/package.json
=> Updated packages

public-site/docs/docs/topic-private-link/index.md, public-site/docs/guides/private-link/index.md
http://localhost:8000/guides/private-link/
http://localhost:8000/docs/topic-private-link/
=> docs: Update private link documentation to clarify shared links and authentication

public-site/docs/guides/authentication/index.md, public-site/docs/guides/deploy-only/index.md, public-site/docs/radix-config/index.md
Remove references to Bitnami and prefer `systemManaged` session store
=> fix: remove bitnami references

public-site/docs/docs/topic-uptime/index.md
Changed a little bit in the text
=> feat: application lifecycle info

public-site/docs/docs/topic-domain-names/index.md, public-site/docs/radix-config/index.md
=> 497 documentation for dns alias
