equinor/radix-public-site

public-site/docs/src/guides/external-alias/index.md
Add example ServiceNow request to demonstrate how to request an intermediate certificate together with your public SSL certificate.
=> Specify how to request public SSL certificate with intermediate

CONTRIBUTING.md, README.md, SECURITY.md
Add security.md
Update readme.md
=> Add contributing.md

public-site/docs/docs/topic-releases/index.md, public-site/docs/radix-config/index.md
Added comment about Keda documentation for cooldown periods and polling interval
=> add comment about keda documentation

radixconfig.yaml
Docusaurus requires a lot of CPU durinit startup. With too low cpu limit, it can take many minutes for the readiness probe to succeed
=> increase cpu limit to speed up startup time

public-site/docs/guides/jobs/configure-jobs.md, public-site/docs/radix-config/index.md, public-site/package-lock.json, public-site/package.json
=> Docs about job schedule batch status

public-site/docs/guides/jobs/job-manager-and-job-api.md, public-site/docs/radix-config/index.md
=> remove-status

public-site/docs/features/index.md, public-site/src/components/RadixTeam/index.tsx
=> Update to features page

public-site/docs/docs/topic-releases/index.md, public-site/docs/start/radix-concepts/index.md
=> info-about-pipeline-job-cleanup-rules

public-site/docs/docs/topic-radix-cli/index.md, public-site/docs/radix-config/index.md, public-site/package-lock.json, public-site/package.json
=> Info about overriding useBuildCache

public-site/docs/guides/git-submodules/index.md, public-site/docs/guides/git-submodules/update-submodule-in-pipeline-job.md
=> Added info about private submodules

public-site/docs/guides/git-submodules/update-submodule-in-pipeline-job.md
=> Fixed missing info

public-site/README.md
Added info about nginx configuration in readme
=> add info in readme about nginx configs

public-site/docs/docs/topic-private-link/index.md
=> Update privatelink doc

public-site/docs/docs/topic-redis/index.md, public-site/docs/guides/authentication/index.md, public-site/sidebars.ts
=> Added info about Redis

public-site/docs/guides/build-secrets/index.md
=> Corrected example

examples/radix-example-oauth-proxy/api/Dockerfile, public-site/docs/guides/jobs/configure-jobs.md, public-site/docs/guides/jobs/job-manager-and-job-api.md, public-site/docs/radix-config/index.md
- Add documentation for `failurePolicy`
- Update Dockerfile base image to node:20-alpine3.21
=> 425 add documentation for job failurepolicy

public-site/docs/radix-config/index.md
=> Add documentation for HealthChecks

public-site/docs/start/not-radix/index.md, public-site/sidebars.ts
=> added when not to use Radix

public-site/docs/guides/sub-pipeline/example-pipeline-with-env-vars-for-envs.md, public-site/docs/guides/sub-pipeline/example-pipeline-with-env-vars.md
=> Corrected examples with params for sub-pipeline

public-site/docs/radix-config/index.md
=> Corrected description of the option credentials

public-site/docs/guides/private-link/index.md
This PR updates Private Link guide to refer to new policy file (`/src/platform/policyConfig/policysets/OPS-Deny-PE-Cross-Subs.json`) in Solum repo, and tries to describe as best as possible where to edit for Playground and Platform/Platform2.
=> docs: Update private link documentation to refer to correct policy file
